# Generated by Django 4.0.4 on 2022-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_nombre', models.CharField(max_length=50, verbose_name='Nombre alumno')),
                ('alumno_apellido', models.CharField(max_length=50, verbose_name='Apellido alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('clase_nombre', models.CharField(max_length=50, verbose_name='Nombre clase')),
            ],
        ),
    ]
