# Generated by Django 4.0.4 on 2022-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_edad',
            field=models.CharField(max_length=50, null=True, verbose_name='Edad alumno'),
        ),
    ]
