# Generated by Django 4.0.4 on 2022-05-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alumno_alumno_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='alumno_edad',
        ),
    ]
